# Generated by Django 3.1 on 2020-08-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tubify',
            name='v_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tubify',
            name='v_thumb',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tubify',
            name='v_views',
            field=models.CharField(max_length=128),
        ),
    ]
